# fly.toml app configuration file generated for booking-pal-service on 2023-11-01T15:01:53+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "booking-pal-service"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
